apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-interlace-controller
  template:
    metadata:
      labels:
        app: argocd-interlace-controller
    spec:
      serviceAccountName: argocd-interlace-controller
      containers:
        - name: argocd-interlace-controller
          image: ghcr.io/argoproj-labs/argocd-interlace-controller:dev
          imagePullPolicy: Always
          command:
            - argocd-interlace
          args:
            - --namespace=argocd
          volumeMounts:
            - name: output
              mountPath: /tmp/output
            - name: signing-secrets
              mountPath: /etc/signing-secrets
            - name: keyring-secret
              mountPath: /.gnupg/
      volumes:
        - name: signing-secrets
          secret:
            secretName: signing-secrets
        - name: keyring-secret
          secret:
            secretName: keyring-secret
        - name: output
          emptyDir: {}
